spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WhereIsMyMoney
    username: postgres
    password: dsrnjh1
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
  flyway:
    create-schemas: true
#    hibernate:
#      ddl-auto: create-drop

#  mvc:
#    static-path-pattern: /resources/**

server:
  servlet:
    context-path: /api

jwt:
  Secret: SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey
  ExpirationMS: 86400000